{
 "title": "Claptrap",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Event Handle Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" },
      { "params": [ "EventTypeCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__claptrap_event_handling_timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Event Saver Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__claptrap_eventsaver_timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Claptrap Event Loader Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__claptrap_eventloader_timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Claptrap Event Saver Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "alias": "time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" }
     ],
     "measurement": "application__claptrap_eventsaver_timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "count derivative",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" }
     ],
     "measurement": "application__claptrap_eventsaver_timer",
     "select": [
      [
       { "params": [ "count.hist" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ]
    },
    {
     "alias": "count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" }
     ],
     "measurement": "application__claptrap_eventsaver_timer",
     "select": [
      [
       { "params": [ "count.hist" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Claptrap State Loader Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__claptrap_stateloader_timer",
     "select": [
      [
       { "params": [ "median" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Claptrap State Saver Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__claptrap_statesaver_timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Claptrap Activation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__claptrap_activation_timer",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Claptrap Deactivation Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__claptrap_deactivation_timer",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Event Handle Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" },
      { "params": [ "EventTypeCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__claptrap_event_handling_timer",
     "select": [
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Event Handle Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ClaptrapTypeCode" ], "type": "tag" },
      { "params": [ "EventTypeCode" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application__claptrap_event_handling_timer",
     "select": [
      [
       { "params": [ "count.hist" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } }
 ]
}