version: '3.3'

services:

    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password --local-infile=1
        restart: always
        ports:
            - 33306:3306
        environment:
            MYSQL_ROOT_PASSWORD: claptrap
        volumes:
            - ./mysql:/docker-entrypoint-initdb.d

    adminer:
        image: adminer
        restart: always
        ports:
            - 38095:8080