version: '3.4'

services:
  redis:
    image: redis:alpine

  zipkin:
    image: openzipkin/zipkin-slim

  actorhost:
    image: ${DOCKER_REGISTRY-}helloclaptrapbackendserver
    build:
      context: .
      dockerfile: HelloClaptrap.BackendServer/Dockerfile
    depends_on:
      - dapr-placement

  actorhost-dapr:
    image: "daprio/daprd:1.0.0-rc.2"
    network_mode: "service:actorhost"
    depends_on:
      - actorhost

  webapi:
    image: ${DOCKER_REGISTRY-}helloclaptrapweb
    build:
      context: .
      dockerfile: HelloClaptrap.Web/Dockerfile

  webapi-dapr:
    image: "daprio/daprd:1.0.0-rc.2"
    network_mode: "service:webapi"
    depends_on:
      - webapi

  dapr-placement:
    image: "daprio/placement:1.0.0-rc.2"
    