version: '3.3'

services:

    mongo:
        image: mongo
        restart: always
        ports:
            - 27999:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: claptrap

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 38091:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: claptrap