apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: actor-statestore
  namespace: default
spec:
  type: state.redis
  metadata:
    - name: redisHost
      value: redis:16379
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
