version: '3.3'

services:

    grafana:
        image: grafana/grafana
        ports:
            - 3000:3000
    influxdb:
        image: influxdb
        ports: 
            - 19086:8086
        environment: 
            INFLUXDB_DB: metricsdatabase
            INFLUXDB_ADMIN_USER: claptrap
            INFLUXDB_ADMIN_PASSWORD: claptrap
