name: benchmark_db_event_saving_webapi_sqlite

on:
  push:
    branches:
      - feature/k6

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0" # SDK Version to use; x will use the latest version of the 3.1 channel
      - run: |
          cd $GITHUB_WORKSPACE/src/Newbe.Claptrap.StorageTestWebApi
          docker build . -t mywebapi

  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    services:
      webapi:
        image: mywebapi
        # env:
        #   POSTGRES_PASSWORD: claptrap
        #   POSTGRES_DB: claptrap
        # ports:
        #   - 5432
        # options: >-
        #   --health-cmd pg_isready
        #   --health-interval 10s
        #   --health-timeout 5s
        #   --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - run: |
          echo ls
