name: Claptrap build

on:
  push:
    branches:
      - feature/database_postgresql

jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0
    services:
      postgres:
        image: postgres:12.3-alpine
        env:
          POSTGRES_PASSWORD: claptrap
          POSTGRES_DB: claptrap
        ports:
          - 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Build
        run: |
          dotnet build $GITHUB_WORKSPACE/src --configuration Release
      - name: Test
        run: |
          dotnet test $GITHUB_WORKSPACE/src --configuration Release -l "console;verbosity=detailed" --collect:"XPlat Code Coverage" --settings $GITHUB_WORKSPACE/src/coverlet.runsettings --logger:nunit -- NUnit.Where="Category == PostgreSQL"
      - uses: MirrorNG/nunit-reporter@v1.0.11
        if: always()
        with:
          path: src/*.Tests/TestResults/*.xml
          access-token: ${{ secrets.GITHUB_TOKEN }}
