name: Claptrap build

on:
  push:
    branches: 
      - feature/database_mongodb
      - feature/ut
    
jobs:
  build:

    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1-alpine
    services:
      mongo:
        image: mongo
        ports:
          - 27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: claptrap
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Build
      run: |
        dotnet build $GITHUB_WORKSPACE/src --configuration Release
    - name: Test
      run: |
        dotnet test $GITHUB_WORKSPACE/src --collect:"XPlat Code Coverage" --settings $GITHUB_WORKSPACE/src/coverlet.runsettings -- NUnit.Where="Category == MongoDB"