name: Claptrap build

on:
  push:
    branches: 
      - feature/database_postgresql
      - feature/ut
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: |
        dotnet build $GITHUB_WORKSPACE/src --configuration Release
    - name: Test
      run: |
        dotnet test $GITHUB_WORKSPACE/src --collect:"XPlat Code Coverage" --settings $GITHUB_WORKSPACE/src/coverlet.runsettings -- NUnit.Where="Category == PostgreSQL"

    services:

      postgres:
        image: postgres:12.3-alpine
        restart: always
        environment:
          POSTGRES_PASSWORD: claptrap
          POSTGRES_USER: claptrap
          POSTGRES_DB: claptrap
        ports:
          - 35432:5432
        volumes:
          - ./postgresql:/docker-entrypoint-initdb.d
      mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
          - 33306:3306
        environment:
          MYSQL_ROOT_PASSWORD: claptrap
        volumes:
          - ./mysql:/docker-entrypoint-initdb.d
  
      mongo:
        image: mongo
        restart: always
        ports:
          - 27017:27017
        environment:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: claptrap