name: Claptrap build

on:
  push:
    branches: 
      - feature/ut
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Setup Postgres database
      uses: Daniel-Marynicz/postgresql-action@master
      with:
        postgres_image_tag: 12-alpine
        app_user: claptrap
        app_user_password: claptrap
        app_db: claptrap
        postgres_extensions: uuid-ossp ltree
        exposed_postgres_port: 35432
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build
      run: |
        dotnet build $GITHUB_WORKSPACE/src --configuration Release
    - name: Test
      run: |
        dotnet test $GITHUB_WORKSPACE/src --collect:"XPlat Code Coverage" --settings $GITHUB_WORKSPACE/src/coverlet.runsettings -- NUnit.Where="Category == PostgreSQL"