name: Claptrap build

on:
  push:
    branches: 
      - feature/rabbitmq
    
jobs:
  build:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/core/sdk:3.1.301-bionic
    services:
      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
          - 5672
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Build
      run: |
        dotnet build $GITHUB_WORKSPACE/src --configuration Release
    - name: Test
      run: |
        dotnet test $GITHUB_WORKSPACE/src --collect:"XPlat Code Coverage" --verbosity d --settings $GITHUB_WORKSPACE/src/coverlet.runsettings -- NUnit.Where="Category == RabbitMQ"

